spring:
    datasource:
        url: mysql://${{ root }}:${{ 5j74dxD4THaWTVQaOohs }}@${{ containers-us-west-147.railway.app }}:${{ 5453 }}/${{ railway }}
        username: root
        password: 5j74dxD4THaWTVQaOohs
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        show-sql: false
        hibernate:
            ddl-auto: update
    thymeleaf:
        cache: false
    mail: 
        host: smtp.gmail.com
        port: 587
        username: apolo.web.page@gmail.com
        password: 
        properties:
            mail:
                smtp:              
                    auth: true
                    starttls:
                        required: true
                        enable: true
server:
    port: 8080